data = [
    r" YLT",
    r"^Aether",
    r"^Amazon Simple Notification Service Agent$",
    r"^Amazon-Route53-Health-Check-Service",
    r"^Amazon CloudFront",
    r"^b0t$",
    r"^bluefish ",
    r"^Calypso v\/",
    r"^COMODO DCV",
    r"^Corax",
    r"^DangDang",
    r"^DavClnt",
    r"^DHSH",
    r"^docker\/[0-9]",
    r"^Expanse",
    r"^FDM ",
    r"^git\/",
    r"^Goose\/",
    r"^Grabber",
    r"^Gradle\/",
    r"^HTTPClient\/",
    r"^HTTPing",
    r"^Java\/",
    r"^Jeode\/",
    r"^Jetty\/",
    r"^Mail\/",
    r"^Mget",
    r"^Microsoft URL Control",
    r"^Mikrotik\/",
    r"^Netlab360",
    r"^NG\/[0-9\.]",
    r"^NING\/",
    r"^npm\/",
    r"^Nuclei",
    r"^PHP-AYMAPI\/",
    r"^PHP\/",
    r"^pip\/",
    r"^pnpm\/",
    r"^RMA\/",
    r"^Ruby|Ruby\/[0-9]",
    r"^symbolicator\/",
    r"^Swurl ",
    r"^TLS tester ",
    r"^twine\/",
    r"^ureq",
    r"^VSE\/[0-9]",
    r"^WordPress\.com",
    r"^XRL\/[0-9]",
    r"^ZmEu",
    r"008\/",
    r"13TABS",
    r"192\.comAgent",
    r"2GDPR\/",
    r"2ip\.ru",
    r"404enemy",
    r"7Siters",
    r"80legs",
    r"a3logics\.in",
    r"A6-Indexer",
    r"Abonti",
    r"Aboundex",
    r"aboutthedomain",
    r"Accoona-AI-Agent",
    r"acebookexternalhit\/",
    r"acoon",
    r"acrylicapps\.com\/pulp",
    r"Acunetix",
    r"AdAuth\/",
    r"adbeat",
    r"AddThis",
    r"ADmantX",
    r"AdminLabs",
    r"adressendeutschland",
    r"adreview\/",
    r"adscanner",
    r"adstxt-worker",
    r"Adstxtaggregator",
    r"adstxt\.com",
    r"Adyen HttpClient",
    r"AffiliateLabz\/",
    r"affilimate-puppeteer",
    r"agentslug",
    r"AHC",
    r"aihit",
    r"aiohttp\/",
    r"Airmail",
    r"akka-http\/",
    r"akula\/",
    r"alertra",
    r"alexa site audit",
    r"Alibaba\.Security\.Heimdall",
    r"Alligator",
    r"allloadin",
    r"AllSubmitter",
    r"alyze\.info",
    r"amagit",
    r"Anarchie",
    r"AndroidDownloadManager",
    r"Anemone",
    r"AngleSharp",
    r"annotate_google",
    r"Anthill",
    r"Anturis Agent",
    r"Ant\.com",
    r"AnyEvent-HTTP\/",
    r"Apache Ant\/",
    r"Apache Droid",
    r"Apache OpenOffice",
    r"Apache-HttpAsyncClient",
    r"Apache-HttpClient",
    r"ApacheBench",
    r"Apexoo",
    r"apimon\.de",
    r"APIs-Google",
    r"AportWorm\/",
    r"AppBeat\/",
    r"AppEngine-Google",
    r"AppleSyndication",
    r"Aprc\/[0-9]",
    r"Arachmo",
    r"arachnode",
    r"Arachnophilia",
    r"aria2",
    r"Arukereso",
    r"asafaweb",
    r"Asana\/",
    r"Ask Jeeves",
    r"AskQuickly",
    r"ASPSeek",
    r"Asterias",
    r"Astute",
    r"asynchttp",
    r"Attach",
    r"attohttpc",
    r"autocite",
    r"AutomaticWPTester",
    r"Autonomy",
    r"awin\.com",
    r"AWS Security Scanner",
    r"axios\/",
    r"a\.pr-cy\.ru",
    r"B-l-i-t-z-B-O-T",
    r"Backlink-Ceck",
    r"BacklinkHttpStatus",
    r"BackStreet",
    r"BackupLand",
    r"BackWeb",
    r"Bad-Neighborhood",
    r"Badass",
    r"baidu\.com",
    r"Bandit",
    r"Barracuda Sentinel \(EE\)",
    r"basicstate",
    r"BatchFTP",
    r"Battleztar Bazinga",
    r"baypup\/",
    r"BazQux",
    r"BBBike",
    r"BCKLINKS",
    r"BDFetch",
    r"BegunAdvertising",
    r"Bewica-security-scan",
    r"Bidtellect",
    r"BigBozz",
    r"Bigfoot",
    r"biglotron",
    r"BingLocalSearch",
    r"BingPreview",
    r"binlar",
    r"biNu image cacher",
    r"Bitacle",
    r"Bitrix link preview",
    r"biz_Directory",
    r"BKCTwitterUnshortener\/",
    r"Black Hole",
    r"Blackboard Safeassign",
    r"BlackWidow",
    r"BlockNote\.Net",
    r"BlogBridge",
    r"Bloglines",
    r"Bloglovin",
    r"BlogPulseLive",
    r"BlogSearch",
    r"Blogtrottr",
    r"BlowFish",
    r"boitho\.com-dc",
    r"Boost\.Beast",
    r"BPImageWalker",
    r"Braintree-Webhooks",
    r"Branch Metrics API",
    r"Branch-Passthrough",
    r"Brandprotect",
    r"Brandwatch",
    r"Brodie\/",
    r"Browsershots",
    r"BUbiNG",
    r"Buck\/",
    r"Buddy",
    r"BuiltWith",
    r"Bullseye",
    r"BunnySlippers",
    r"Burf Search",
    r"Butterfly\/",
    r"BuzzSumo",
    r"CAAM\/[0-9]",
    r"caam dot crwlr at gmail dot com",
    r"CakePHP",
    r"Calculon",
    r"Canary%20Mail",
    r"CaretNail",
    r"catexplorador",
    r"CC Metadata Scaper",
    r"Cegbfeieh",
    r"censys",
    r"centuryb.o.t9[at]gmail.com",
    r"Cerberian Drtrs",
    r"CERT\.at-Statistics-Survey",
    r"cf-facebook",
    r"cg-eye",
    r"changedetection",
    r"ChangesMeter",
    r"Charlotte",
    r"chatterino-api-cache",
    r"CheckHost",
    r"checkprivacy",
    r"CherryPicker",
    r"ChinaClaw",
    r"Chirp\/",
    r"chkme\.com",
    r"Chlooe",
    r"Chromaxa",
    r"CirrusExplorer",
    r"CISPA Vulnerability Notification",
    r"CISPA Web Analyser",
    r"Citoid",
    r"CJNetworkQuality",
    r"Clarsentia",
    r"clips\.ua\.ac\.be",
    r"Cloud mapping",
    r"CloudEndure",
    r"CloudFlare-AlwaysOnline",
    r"Cloudflare-Healthchecks",
    r"Cloudinary",
    r"cmcm\.com",
    r"coccoc",
    r"cognitiveseo",
    r"ColdFusion",
    r"colly -",
    r"CommaFeed",
    r"Commons-HttpClient",
    r"commonscan",
    r"contactbigdatafr",
    r"contentkingapp",
    r"Contextual Code Sites Explorer",
    r"convera",
    r"CookieReports",
    r"copyright sheriff",
    r"CopyRightCheck",
    r"Copyscape",
    r"cortex\/",
    r"Cosmos4j\.feedback",
    r"Covario-IDS",
    r"Craw\/",
    r"Crescent",
    r"Criteo",
    r"Crowsnest",
    r"CSHttp",
    r"CSSCheck",
    r"Cula\/",
    r"curb",
    r"Curious George",
    r"curl",
    r"cuwhois\/",
    r"cybo\.com",
    r"DAP\/NetHTTP",
    r"DareBoost",
    r"DatabaseDriverMysqli",
    r"DataCha0s",
    r"DatadogSynthetics",
    r"Datafeedwatch",
    r"Datanyze",
    r"DataparkSearch",
    r"dataprovider",
    r"DataXu",
    r"Daum(oa)?[ \/][0-9]",
    r"dBpoweramp",
    r"ddline",
    r"deeris",
    r"delve\.ai",
    r"Demon",
    r"DeuSu",
    r"developers\.google\.com\/\+\/web\/snippet\/",
    r"Devil",
    r"Digg",
    r"Digincore",
    r"DigitalPebble",
    r"Dirbuster",
    r"Discourse Forum Onebox",
    r"Dispatch\/",
    r"Disqus\/",
    r"DittoSpyder",
    r"dlvr",
    r"DMBrowser",
    r"DNSPod-reporting",
    r"docoloc",
    r"Dolphin http client",
    r"DomainAppender",
    r"DomainLabz",
    r"Domains Project\/",
    r"Donuts Content Explorer",
    r"dotMailer content retrieval",
    r"dotSemantic",
    r"downforeveryoneorjustme",
    r"Download Wonder",
    r"downnotifier",
    r"DowntimeDetector",
    r"Drip",
    r"drupact",
    r"Drupal \(\+http:\/\/drupal\.org\/\)",
    r"DTS Agent",
    r"dubaiindex",
    r"DuplexWeb-Google",
    r"DynatraceSynthetic",
    r"EARTHCOM",
    r"Easy-Thumb",
    r"EasyDL",
    r"Ebingbong",
    r"ec2linkfinder",
    r"eCairn-Grabber",
    r"eCatch",
    r"ECCP",
    r"eContext\/",
    r"Ecxi",
    r"EirGrabber",
    r"ElectricMonk",
    r"elefent",
    r"EMail Exractor",
    r"EMail Wolf",
    r"EmailWolf",
    r"Embarcadero",
    r"Embed PHP Library",
    r"Embedly",
    r"endo\/",
    r"europarchive\.org",
    r"evc-batch",
    r"EventMachine HttpClient",
    r"Everwall Link Expander",
    r"Evidon",
    r"Evrinid",
    r"ExactSearch",
    r"ExaleadCloudview",
    r"Excel\/",
    r"exif",
    r"ExoRank",
    r"Exploratodo",
    r"Express WebPictures",
    r"Extreme Picture Finder",
    r"EyeNetIE",
    r"ezooms",
    r"facebookcatalog",
    r"facebookexternalhit",
    r"facebookexternalua",
    r"facebookplatform",
    r"fairshare",
    r"Faraday v",
    r"fasthttp",
    r"Faveeo",
    r"Favicon downloader",
    r"faviconarchive",
    r"faviconkit",
    r"FavOrg",
    r"Feed Wrangler",
    r"Feedable\/",
    r"Feedbin",
    r"FeedBooster",
    r"FeedBucket",
    r"FeedBunch\/",
    r"FeedBurner",
    r"feeder",
    r"Feedly",
    r"FeedshowOnline",
    r"Feedshow\/",
    r"Feedspot",
    r"FeedViewer\/",
    r"Feedwind\/",
    r"FeedZcollector",
    r"feeltiptop",
    r"Fetch API",
    r"Fetch\/[0-9]",
    r"Fever\/[0-9]",
    r"FHscan",
    r"Fiery%20Feeds",
    r"Filestack",
    r"Fimap",
    r"findlink",
    r"findthatfile",
    r"FlashGet",
    r"FlipboardBrowserProxy",
    r"FlipboardProxy",
    r"FlipboardRSS",
    r"Flock\/",
    r"Florienzh\/",
    r"fluffy",
    r"Flunky",
    r"flynxapp",
    r"forensiq",
    r"ForusP",
    r"FoundSeoTool",
    r"fragFINN\.de",
    r"free thumbnails",
    r"Freeuploader",
    r"FreshRSS",
    r"frontman",
    r"Funnelback",
    r"Fuzz Faster U Fool",
    r"G-i-g-a-b-o-t",
    r"g00g1e\.net",
    r"ganarvisitas",
    r"gdnplus\.com",
    r"GeedoProductSearch",
    r"geek-tools",
    r"Genieo",
    r"GentleSource",
    r"GetCode",
    r"Getintent",
    r"GetLinkInfo",
    r"getprismatic",
    r"GetRight",
    r"getroot",
    r"GetURLInfo\/",
    r"GetWeb",
    r"Geziyor",
    r"Ghost Inspector",
    r"GigablastOpenSource",
    r"GIS-LABS",
    r"github-camo",
    r"GitHub-Hookshot",
    r"github\.com",
    r"Go http package",
    r"Go [\d\.]* package http",
    r"Go!Zilla",
    r"Go-Ahead-Got-It",
    r"Go-http-client",
    r"go-mtasts\/",
    r"gobuster",
    r"gobyus",
    r"Gofeed",
    r"gofetch",
    r"Goldfire Server",
    r"GomezAgent",
    r"gooblog",
    r"Goodzer\/",
    r"Google AppsViewer",
    r"Google Desktop",
    r"Google favicon",
    r"Google Keyword Suggestion",
    r"Google Keyword Tool",
    r"Google Page Speed Insights",
    r"Google PP Default",
    r"Google Search Console",
    r"Google Web Preview",
    r"Google-Ads",
    r"Google-Adwords",
    r"Google-Apps-Script",
    r"Google-Calendar-Importer",
    r"Google-HotelAdsVerifier",
    r"Google-HTTP-Java-Client",
    r"Google-InspectionTool",
    r"Google-Podcast",
    r"Google-Publisher-Plugin",
    r"Google-Read-Aloud",
    r"Google-SearchByImage",
    r"Google-Site-Verification",
    r"Google-SMTP-STS",
    r"Google-speakr",
    r"Google-Structured-Data-Testing-Tool",
    r"Google-Transparency-Report",
    r"google-xrawler",
    r"Google-Youtube-Links",
    r"GoogleDocs",
    r"GoogleHC\/",
    r"GoogleOther",
    r"GoogleProber",
    r"GoogleProducer",
    r"GoogleSites",
    r"Gookey",
    r"GoSpotCheck",
    r"gosquared-thumbnailer",
    r"Gotit",
    r"GoZilla",
    r"grabify",
    r"GrabNet",
    r"Grafula",
    r"Grammarly",
    r"GrapeFX",
    r"GreatNews",
    r"Gregarius",
    r"GRequests",
    r"grokkit",
    r"grouphigh",
    r"grub-client",
    r"gSOAP\/",
    r"GT::WWW",
    r"GTmetrix",
    r"GuzzleHttp",
    r"gvfs\/",
    r"HAA(A)?RTLAND http client",
    r"Haansoft",
    r"hackney\/",
    r"Hadi Agent",
    r"HappyApps-WebCheck",
    r"Hardenize",
    r"Hatena",
    r"Havij",
    r"HaxerMen",
    r"HeadlessChrome",
    r"HEADMasterSEO",
    r"HeartRails_Capture",
    r"help@dataminr\.com",
    r"heritrix",
    r"Hexometer",
    r"historious",
    r"hkedcity",
    r"hledejLevne\.cz",
    r"Hloader",
    r"HMView",
    r"Holmes",
    r"HonesoSearchEngine",
    r"HootSuite Image proxy",
    r"Hootsuite-WebFeed",
    r"hosterstats",
    r"HostTracker",
    r"ht:\/\/check",
    r"htdig",
    r"HTMLparser",
    r"htmlyse",
    r"HTTP Banner Detection",
    r"http-get",
    r"HTTP-Header-Abfrage",
    r"http-kit",
    r"http-request\/",
    r"HTTP-Tiny",
    r"HTTP::Lite",
    r"http:\/\/www.neomo.de\/",
    r"HttpComponents",
    r"httphr",
    r"HTTPie",
    r"HTTPMon",
    r"httpRequest",
    r"httpscheck",
    r"httpssites_power",
    r"httpunit",
    r"HttpUrlConnection",
    r"http\.rb\/",
    r"HTTP_Compression_Test",
    r"http_get",
    r"http_request2",
    r"http_requester",
    r"httrack",
    r"huaweisymantec",
    r"HubSpot ",
    r"HubSpot-Link-Resolver",
    r"Humanlinks",
    r"i2kconnect\/",
    r"Iblog",
    r"ichiro",
    r"Id-search",
    r"IdeelaborPlagiaat",
    r"IDG Twitter Links Resolver",
    r"IDwhois\/",
    r"Iframely",
    r"igdeSpyder",
    r"iGooglePortal",
    r"IlTrovatore",
    r"Image Fetch",
    r"Image Sucker",
    r"ImageEngine\/",
    r"ImageVisu\/",
    r"Imagga",
    r"imagineeasy",
    r"imgsizer",
    r"InAGist",
    r"inbound\.li parser",
    r"InDesign%20CC",
    r"Indy Library",
    r"InetURL",
    r"infegy",
    r"infohelfer",
    r"InfoTekies",
    r"InfoWizards Reciprocal Link",
    r"inpwrd\.com",
    r"instabid",
    r"Instapaper",
    r"Integrity",
    r"integromedb",
    r"Intelliseek",
    r"InterGET",
    r"Internet Ninja",
    r"InternetSeer",
    r"internetVista monitor",
    r"internetwache",
    r"internet_archive",
    r"intraVnews",
    r"IODC",
    r"IOI",
    r"Inboxb0t",
    r"iplabel",
    r"ips-agent",
    r"IPS\/[0-9]",
    r"IPWorks HTTP\/S Component",
    r"iqdb\/",
    r"Iria",
    r"Irokez",
    r"isitup\.org",
    r"iskanie",
    r"isUp\.li",
    r"iThemes Sync\/",
    r"IZaBEE",
    r"iZSearch",
    r"JAHHO",
    r"janforman",
    r"Jaunt\/",
    r"Java.*outbrain",
    r"javelin\.io",
    r"Jbrofuzz",
    r"Jersey\/",
    r"JetCar",
    r"Jigsaw",
    r"Jobboerse",
    r"JobFeed discovery",
    r"Jobg8 URL Monitor",
    r"jobo",
    r"Jobrapido",
    r"Jobsearch1\.5",
    r"JoinVision Generic",
    r"JolokiaPwn",
    r"Joomla",
    r"Jorgee",
    r"JS-Kit",
    r"JungleKeyThumbnail",
    r"JustView",
    r"Kaspersky Lab CFR link resolver",
    r"Kelny\/",
    r"Kerrigan\/",
    r"KeyCDN",
    r"Keyword Density",
    r"Keywords Research",
    r"khttp\/",
    r"KickFire",
    r"KimonoLabs\/",
    r"Kml-Google",
    r"knows\.is",
    r"KOCMOHABT",
    r"kouio",
    r"krawler\.dk",
    r"kube-probe",
    r"kubectl",
    r"kulturarw3",
    r"KumKie",
    r"Larbin",
    r"Lavf\/",
    r"leakix\.net",
    r"LeechFTP",
    r"LeechGet",
    r"letsencrypt",
    r"Lftp",
    r"LibVLC",
    r"LibWeb",
    r"Libwhisker",
    r"libwww",
    r"Licorne",
    r"Liferea\/",
    r"Lighthouse",
    r"Lightspeedsystems",
    r"Likse",
    r"limber\.io",
    r"Link Valet",
    r"LinkAlarm\/",
    r"LinkAnalyser",
    r"link-check",
    r"linkCheck",
    r"linkdex",
    r"LinkExaminer",
    r"linkfluence",
    r"linkpeek",
    r"LinkPreview",
    r"LinkScan",
    r"LinksManager",
    r"LinkTiger",
    r"LinkWalker",
    r"link_thumbnailer",
    r"Lipperhey",
    r"Litemage_walker",
    r"livedoor ScreenShot",
    r"LoadImpactRload",
    r"localsearch-web",
    r"LongURL API",
    r"longurl-r-package",
    r"looid\.com",
    r"looksystems\.net",
    r"lscache_runner",
    r"ltx71",
    r"lua-resty-http",
    r"Lucee \(CFML Engine\)",
    r"Lush Http Client",
    r"lwp-request",
    r"lwp-trivial",
    r"LWP::Simple",
    r"lycos",
    r"LYT\.SR",
    r"L\.webis",
    r"mabontland",
    r"MacOutlook\/",
    r"MagentaNews\/",
    r"Mag-Net",
    r"MagpieRSS",
    r"Mail::STS",
    r"MailChimp",
    r"Mail\.Ru",
    r"Majestic12",
    r"makecontact\/",
    r"Mandrill",
    r"MapperCmd",
    r"marketinggrader",
    r"MarkMonitor",
    r"MarkWatch",
    r"Mass Downloader",
    r"masscan\/",
    r"Mata Hari",
    r"mattermost",
    r"MatchorySearch\/",
    r"Mediametric",
    r"Mediapartners-Google",
    r"mediawords",
    r"MegaIndex\.ru",
    r"MeltwaterNews",
    r"Melvil Rawi",
    r"MemGator",
    r"Metaspinner",
    r"MetaURI",
    r"MFC_Tear_Sample",
    r"Microsearch",
    r"Microsoft Data Access",
    r"Microsoft Office",
    r"Microsoft Outlook",
    r"Microsoft Windows Network Diagnostics",
    r"Microsoft-WebDAV-MiniRedir",
    r"Microsoft\.Data\.Mashup",
    r"MicrosoftPreview",
    r"MIDown tool",
    r"MIIxpc",
    r"Mindjet",
    r"Miniature\.io",
    r"Miniflux",
    r"mio_httpc",
    r"Miro-HttpClient",
    r"Mister PiX",
    r"mixdata dot com",
    r"mixed-content-scan",
    r"mixnode",
    r"Mnogosearch",
    r"mogimogi",
    r"Mojeek",
    r"Mojolicious \(Perl\)",
    r"Mollie",
    r"monitis",
    r"Monitority\/",
    r"Monit\/",
    r"montastic",
    r"MonTools",
    r"Moreover",
    r"Morfeus Fucking Scanner",
    r"Morning Paper",
    r"MovableType",
    r"mowser",
    r"Mrcgiguy",
    r"Mr\.4x3 Powered",
    r"MS Web Services Client Protocol",
    r"MSFrontPage",
    r"mShots",
    r"MuckRack\/",
    r"muhstik-scan",
    r"MVAClient",
    r"MxToolbox\/",
    r"myseosnapshot",
    r"nagios",
    r"Najdi\.si",
    r"Name Intelligence",
    r"NameFo\.com",
    r"Nameprotect",
    r"nationalarchives",
    r"Navroad",
    r"nbertaupete95",
    r"NearSite",
    r"Needle",
    r"Nessus",
    r"Net Vampire",
    r"NetAnts",
    r"NETCRAFT",
    r"NetLyzer",
    r"NetMechanic",
    r"NetNewsWire",
    r"Netpursual",
    r"netresearch",
    r"NetShelter ContentScan",
    r"Netsparker",
    r"NetSystemsResearch",
    r"nettle",
    r"NetTrack",
    r"Netvibes",
    r"NetZIP",
    r"Neustar WPM",
    r"NeutrinoAPI",
    r"NewRelicPinger",
    r"NewsBlur .*Finder",
    r"NewsGator",
    r"newsme",
    r"newspaper\/",
    r"Nexgate Ruby Client",
    r"NG-Search",
    r"nghttp2",
    r"Nibbler",
    r"NICErsPRO",
    r"NihilScio",
    r"Nikto",
    r"nineconnections",
    r"NLNZ_IAHarvester",
    r"Nmap Scripting Engine",
    r"node-fetch",
    r"node-superagent",
    r"node-urllib",
    r"Nodemeter",
    r"NodePing",
    r"node\.io",
    r"nominet\.org\.uk",
    r"nominet\.uk",
    r"Norton-Safeweb",
    r"Notifixious",
    r"notifyninja",
    r"NotionEmbedder",
    r"nuhk",
    r"nutch",
    r"Nuzzel",
    r"nWormFeedFinder",
    r"nyawc\/",
    r"Nymesis",
    r"NYU",
    r"Observatory\/",
    r"Ocelli\/",
    r"Octopus",
    r"oegp",
    r"Offline Explorer",
    r"Offline Navigator",
    r"OgScrper",
    r"okhttp",
    r"omgili",
    r"OMSC",
    r"Online Domain Tools",
    r"Open Source RSS",
    r"OpenCalaisSemanticProxy",
    r"Openfind",
    r"OpenLinkProfiler",
    r"Openstat\/",
    r"OpenVAS",
    r"OPPO A33",
    r"Optimizer",
    r"Orbiter",
    r"OrgProbe\/",
    r"orion-semantics",
    r"Outlook-Express",
    r"Outlook-iOS",
    r"Owler",
    r"Owlin",
    r"ownCloud News",
    r"ow\.ly",
    r"OxfordCloudService",
    r"page scorer",
    r"Page Valet",
    r"page2rss",
    r"PageFreezer",
    r"PageGrabber",
    r"PagePeeker",
    r"PageScorer",
    r"Pagespeed\/",
    r"PageThing",
    r"page_verifier",
    r"Panopta",
    r"panscient",
    r"Papa Foto",
    r"parsijoo",
    r"Pavuk",
    r"PayPal IPN",
    r"pcBrowser",
    r"Pcore-HTTP",
    r"PDF24 URL To PDF",
    r"Pearltrees",
    r"PECL::HTTP",
    r"peerindex",
    r"Peew",
    r"PeoplePal",
    r"Perlu -",
    r"PhantomJS Screenshoter",
    r"PhantomJS\/",
    r"Photon\/",
    r"php-requests",
    r"phpservermon",
    r"Pi-Monster",
    r"Picscout",
    r"Picsearch",
    r"PictureFinder",
    r"Pimonster",
    r"Pingability",
    r"PingAdmin\.Ru",
    r"Pingdom",
    r"Pingoscope",
    r"PingSpot",
    r"ping\.blo\.gs",
    r"pinterest\.com",
    r"Pixray",
    r"Pizilla",
    r"Plagger\/",
    r"Pleroma ",
    r"Ploetz \+ Zeller",
    r"Plukkie",
    r"plumanalytics",
    r"PocketImageCache",
    r"PocketParser",
    r"Pockey",
    r"PodcastAddict\/",
    r"POE-Component-Client-HTTP",
    r"Polymail\/",
    r"Pompos",
    r"Porkbun",
    r"Port Monitor",
    r"postano",
    r"postfix-mta-sts-resolver",
    r"PostmanRuntime",
    r"postplanner\.com",
    r"PostPost",
    r"postrank",
    r"PowerPoint\/",
    r"Prebid",
    r"Prerender",
    r"Priceonomics Analysis Engine",
    r"PrintFriendly",
    r"PritTorrent",
    r"Prlog",
    r"probely\.com",
    r"probethenet",
    r"Project ?25499",
    r"Project-Resonance",
    r"prospectb2b",
    r"Protopage",
    r"ProWebWalker",
    r"proximic",
    r"PRTG Network Monitor",
    r"pshtt, https scanning",
    r"PTST ",
    r"PTST\/[0-9]+",
    r"pulsetic\.com",
    r"Pump",
    r"Python-httplib2",
    r"python-httpx",
    r"python-requests",
    r"Python-urllib",
    r"Qirina Hurdler",
    r"QQDownload",
    r"QrafterPro",
    r"Qseero",
    r"Qualidator",
    r"QueryN Metasearch",
    r"queuedriver",
    r"quic-go-HTTP\/",
    r"QuiteRSS",
    r"Quora Link Preview",
    r"Qwantify",
    r"Radian6",
    r"RadioPublicImageResizer",
    r"Railgun\/",
    r"RankActive",
    r"RankFlex",
    r"RankSonicSiteAuditor",
    r"RapidLoad\/",
    r"Re-re Studio",
    r"ReactorNetty",
    r"Readability",
    r"RealDownload",
    r"RealPlayer%20Downloader",
    r"RebelMouse",
    r"Recorder",
    r"RecurPost\/",
    r"redback\/",
    r"ReederForMac",
    r"Reeder\/",
    r"ReGet",
    r"RepoMonkey",
    r"request\.js",
    r"reqwest\/",
    r"ResponseCodeTest",
    r"RestSharp",
    r"Riddler",
    r"Rival IQ",
    r"Robosourcer",
    r"Robozilla",
    r"ROI Hunter",
    r"RPT-HTTPClient",
    r"RSSMix\/",
    r"RSSOwl",
    r"RuxitSynthetic",
    r"RyowlEngine",
    r"safe-agent-scanner",
    r"SalesIntelligent",
    r"Saleslift",
    r"SAP NetWeaver Application Server",
    r"SauceNAO",
    r"SBIder",
    r"sc-downloader",
    r"scalaj-http",
    r"Scamadviser-Frontend",
    r"ScanAlert",
    r"scan\.lol",
    r"Scoop",
    r"scooter",
    r"ScopeContentAG-HTTP-Client",
    r"ScoutJet",
    r"ScoutURLMonitor",
    r"ScrapeBox Page Scanner",
    r"Scrapy",
    r"Screaming",
    r"ScreenShotService",
    r"Scrubby",
    r"Scrutiny\/",
    r"Search37",
    r"searchenginepromotionhelp",
    r"Searchestate",
    r"SearchExpress",
    r"SearchSight",
    r"SearchWP",
    r"search\.thunderstone",
    r"Seeker",
    r"semanticdiscovery",
    r"semanticjuice",
    r"Semiocast HTTP client",
    r"Semrush",
    r"Sendsay\.Ru",
    r"sentry\/",
    r"SEO Browser",
    r"Seo Servis",
    r"seo-nastroj\.cz",
    r"seo4ajax",
    r"Seobility",
    r"SEOCentro",
    r"SeoCheck",
    r"seocompany",
    r"SEOkicks",
    r"SEOlizer",
    r"Seomoz",
    r"SEOprofiler",
    r"seoscanners",
    r"SEOsearch",
    r"seositecheckup",
    r"SEOstats",
    r"servernfo",
    r"sexsearcher",
    r"Seznam",
    r"Shelob",
    r"Shodan",
    r"Shoppimon",
    r"ShopWiki",
    r"ShortLinkTranslate",
    r"shortURL lengthener",
    r"shrinktheweb",
    r"Sideqik",
    r"Siege",
    r"SimplePie",
    r"SimplyFast",
    r"Siphon",
    r"SISTRIX",
    r"Site Sucker",
    r"Site-Shot\/",
    r"Site24x7",
    r"SiteBar",
    r"Sitebeam",
    r"Sitebulb\/",
    r"SiteCondor",
    r"SiteExplorer",
    r"SiteGuardian",
    r"Siteimprove",
    r"SiteIndexed",
    r"Sitemap(s)? Generator",
    r"SitemapGenerator",
    r"SiteMonitor",
    r"Siteshooter B0t",
    r"SiteSnagger",
    r"SiteSucker",
    r"SiteTruth",
    r"Sitevigil",
    r"sitexy\.com",
    r"SkypeUriPreview",
    r"Slack\/",
    r"sli-systems\.com",
    r"slider\.com",
    r"slurp",
    r"SlySearch",
    r"SmartDownload",
    r"SMRF URL Expander",
    r"SMUrlExpander",
    r"Snake",
    r"Snappy",
    r"SnapSearch",
    r"Snarfer\/",
    r"SniffRSS",
    r"sniptracker",
    r"Snoopy",
    r"SnowHaze Search",
    r"sogou web",
    r"SortSite",
    r"Sottopop",
    r"sovereign\.ai",
    r"SpaceBison",
    r"SpamExperts",
    r"Spammen",
    r"Spanner",
    r"Spawning-AI",
    r"spaziodati",
    r"SPDYCheck",
    r"Specificfeeds",
    r"SpeedKit",
    r"speedy",
    r"SPEng",
    r"Spinn3r",
    r"spray-can",
    r"Sprinklr ",
    r"spyonweb",
    r"sqlmap",
    r"Sqlworm",
    r"Sqworm",
    r"SSL Labs",
    r"ssl-tools",
    r"StackRambler",
    r"Statastico\/",
    r"Statically-",
    r"StatusCake",
    r"Steeler",
    r"Stratagems Kumo",
    r"Stripe\/",
    r"Stroke\.cz",
    r"StudioFACA",
    r"StumbleUpon",
    r"suchen",
    r"Sucuri",
    r"summify",
    r"SuperHTTP",
    r"Surphace Scout",
    r"Suzuran",
    r"swcd ",
    r"Symfony BrowserKit",
    r"Symfony2 BrowserKit",
    r"Synapse\/",
    r"Syndirella\/",
    r"SynHttpClient-Built",
    r"Sysomos",
    r"sysscan",
    r"Szukacz",
    r"T0PHackTeam",
    r"tAkeOut",
    r"Tarantula\/",
    r"Taringa UGC",
    r"TarmotGezgin",
    r"tchelebi\.io",
    r"techiaith\.cymru",
    r"Teleport",
    r"Telesoft",
    r"Telesphoreo",
    r"Telesphorep",
    r"Tenon\.io",
    r"teoma",
    r"terrainformatica",
    r"Test Certificate Info",
    r"testuri",
    r"Tetrahedron",
    r"TextRazor Downloader",
    r"The Drop Reaper",
    r"The Expert HTML Source Viewer",
    r"The Intraformant",
    r"The Knowledge AI",
    r"theinternetrules",
    r"TheNomad",
    r"Thinklab",
    r"Thumbor",
    r"Thumbshots",
    r"ThumbSniper",
    r"timewe\.net",
    r"TinEye",
    r"Tiny Tiny RSS",
    r"TLSProbe\/",
    r"Toata",
    r"topster",
    r"touche\.com",
    r"Traackr\.com",
    r"tracemyfile",
    r"Trackuity",
    r"TrapitAgent",
    r"Trendiction",
    r"Trendsmap",
    r"trendspottr",
    r"truwoGPS",
    r"TryJsoup",
    r"TulipChain",
    r"Turingos",
    r"Turnitin",
    r"tweetedtimes",
    r"Tweetminster",
    r"Tweezler\/",
    r"twibble",
    r"Twice",
    r"Twikle",
    r"Twingly",
    r"Twisted PageGetter",
    r"Typhoeus",
    r"ubermetrics-technologies",
    r"uclassify",
    r"UdmSearch",
    r"ultimate_sitemap_parser",
    r"unchaos",
    r"unirest-java",
    r"UniversalFeedParser",
    r"unshortenit",
    r"Unshorten\.It",
    r"Untiny",
    r"UnwindFetchor",
    r"updated",
    r"updown\.io daemon",
    r"Upflow",
    r"Uptimia",
    r"URL Verifier",
    r"Urlcheckr",
    r"URLitor",
    r"urlresolver",
    r"Urlstat",
    r"URLTester",
    r"UrlTrends Ranking Updater",
    r"URLy Warning",
    r"URLy\.Warning",
    r"URL\/Emacs",
    r"Vacuum",
    r"Vagabondo",
    r"VB Project",
    r"vBSEO",
    r"VCI",
    r"Verity",
    r"via ggpht\.com GoogleImageProxy",
    r"Virusdie",
    r"visionutils",
    r"Visual Rights Group",
    r"vkShare",
    r"VoidEYE",
    r"Voil",
    r"voltron",
    r"voyager\/",
    r"VSAgent\/",
    r"VSB-TUO\/",
    r"Vulnbusters Meter",
    r"VYU2",
    r"w3af\.org",
    r"W3C-checklink",
    r"W3C-mobileOK",
    r"W3C_Unicorn",
    r"WAC-OFU",
    r"WakeletLinkExpander",
    r"WallpapersHD",
    r"Wallpapers\/[0-9]+",
    r"wangling",
    r"Wappalyzer",
    r"WatchMouse",
    r"WbSrch\/",
    r"WDT\.io",
    r"Web Auto",
    r"Web Collage",
    r"Web Enhancer",
    r"Web Fetch",
    r"Web Fuck",
    r"Web Pix",
    r"Web Sauger",
    r"Web spyder",
    r"Web Sucker",
    r"web-capture\.net",
    r"Web-sniffer",
    r"Webalta",
    r"Webauskunft",
    r"WebAuto",
    r"WebCapture",
    r"WebClient\/",
    r"webcollage",
    r"WebCookies",
    r"WebCopier",
    r"WebCorp",
    r"WebDataStats",
    r"WebDoc",
    r"WebEnhancer",
    r"WebFetch",
    r"WebFuck",
    r"WebGazer",
    r"WebGo IS",
    r"WebImageCollector",
    r"WebImages",
    r"WebIndex",
    r"webkit2png",
    r"WebLeacher",
    r"webmastercoffee",
    r"webmon ",
    r"WebPix",
    r"WebReaper",
    r"WebSauger",
    r"webscreenie",
    r"Webshag",
    r"Webshot",
    r"Website Quester",
    r"websitepulse agent",
    r"WebsiteQuester",
    r"Websnapr",
    r"WebSniffer",
    r"Webster",
    r"WebStripper",
    r"WebSucker",
    r"webtech\/",
    r"WebThumbnail",
    r"Webthumb\/",
    r"WebWhacker",
    r"WebZIP",
    r"WeLikeLinks",
    r"WEPA",
    r"WeSEE",
    r"wf84",
    r"Wfuzz\/",
    r"wget",
    r"WhatCMS",
    r"WhatsApp",
    r"WhatsMyIP",
    r"WhatWeb",
    r"WhereGoes\?",
    r"Whibse",
    r"WhoAPI\/",
    r"WhoRunsCoinHive",
    r"Whynder Magnet",
    r"Windows-RSS-Platform",
    r"WinHttp-Autoproxy-Service",
    r"WinHTTP\/",
    r"WinPodder",
    r"wkhtmlto",
    r"wmtips",
    r"Woko",
    r"Wolfram HTTPClient",
    r"woorankreview",
    r"WordPress\/",
    r"WordupinfoSearch",
    r"Word\/",
    r"worldping-api",
    r"wotbox",
    r"WP Engine Install Performance API",
    r"WP Rocket",
    r"wpif",
    r"wprecon\.com survey",
    r"WPScan",
    r"wscheck",
    r"Wtrace",
    r"WWW-Collector-E",
    r"WWW-Mechanize",
    r"WWW::Document",
    r"WWW::Mechanize",
    r"WWWOFFLE",
    r"www\.monitor\.us",
    r"x09Mozilla",
    r"x22Mozilla",
    r"XaxisSemanticsClassifier",
    r"XenForo\/",
    r"Xenu Link Sleuth",
    r"XING-contenttabreceiver",
    r"xpymep([0-9]?)\.exe",
    r"Y!J-[A-Z][A-Z][A-Z]",
    r"Yaanb",
    r"yacy",
    r"Yahoo Link Preview",
    r"YahooCacheSystem",
    r"YahooMailProxy",
    r"YahooYSMcm",
    r"YandeG",
    r"Yandex(?!Search)",
    r"yanga",
    r"yeti",
    r"Yo-yo",
    r"Yoleo Consumer",
    r"yomins\.com",
    r"yoogliFetchAgent",
    r"YottaaMonitor",
    r"Your-Website-Sucks",
    r"yourls\.org",
    r"YoYs\.net",
    r"YP\.PL",
    r"Zabbix",
    r"Zade",
    r"Zao",
    r"Zapier",
    r"Zauba",
    r"Zemanta Aggregator",
    r"Zend\\Http\\Client",
    r"Zend_Http_Client",
    r"Zermelo",
    r"Zeus ",
    r"zgrab",
    r"ZnajdzFoto",
    r"ZnHTTP",
    r"Zombie\.js",
    r"Zoom\.Mac",
    r"ZoteroTranslationServer",
    r"ZyBorg",
    r"[a-z0-9\-_]*(bot|crawl|archiver|transcoder|spider|uptime|validator|fetcher|cron|checker|reader|extractor|monitoring|analyzer|scraper)",
]
