data = [
    r"HTTP_USER_AGENT",
    r"HTTP_X_OPERAMINI_PHONE_UA",
    r"HTTP_X_DEVICE_USER_AGENT",
    r"HTTP_X_ORIGINAL_USER_AGENT",
    r"HTTP_X_SKYFIRE_PHONE",
    r"HTTP_X_BOLT_PHONE_UA",
    r"HTTP_DEVICE_STOCK_UA",
    r"HTTP_X_UCBROWSER_DEVICE_UA",
    r"HTTP_FROM",
    r"HTTP_X_SCANNER",
    r"HTTP_SEC_CH_UA",
]
